<?php
// All countries
// length 252
$countries_list = array(
    "AF" => array("name" => "Afghanistan", "phone" => "93", "symbol" => "؋"),
    "AX" => array("name" => "Aland Islands", "phone" => "358", "symbol" => "€"),
    "AL" => array("name" => "Albania", "phone" => "355", "symbol" => "Lek"),
    "DZ" => array("name" => "Algeria", "phone" => "213", "symbol" => "دج"),
    "AS" => array("name" => "American Samoa", "phone" => "1684", "symbol" => "$"),
    "AD" => array("name" => "Andorra", "phone" => "376", "symbol" => "€"),
    "AO" => array("name" => "Angola", "phone" => "244", "symbol" => "Kz"),
    "AI" => array("name" => "Anguilla", "phone" => "1264", "symbol" => "$"),
    "AQ" => array("name" => "Antarctica", "phone" => "672", "symbol" => "$"),
    "AG" => array("name" => "Antigua and Barbuda", "phone" => "1268", "symbol" => "$"),
    "AR" => array("name" => "Argentina", "phone" => "54", "symbol" => "$"),
    "AM" => array("name" => "Armenia", "phone" => "374", "symbol" => "֏"),
    "AW" => array("name" => "Aruba", "phone" => "297", "symbol" => "ƒ"),
    "AU" => array("name" => "Australia", "phone" => "61", "symbol" => "$"),
    "AT" => array("name" => "Austria", "phone" => "43", "symbol" => "€"),
    "AZ" => array("name" => "Azerbaijan", "phone" => "994", "symbol" => "m"),
    "BS" => array("name" => "Bahamas", "phone" => "1242", "symbol" => "B$"),
    "BH" => array("name" => "Bahrain", "phone" => "973", "symbol" => ".د.ب"),
    "BD" => array("name" => "Bangladesh", "phone" => "880", "symbol" => "৳"),
    "BB" => array("name" => "Barbados", "phone" => "1246", "symbol" => "Bds$"),
    "BY" => array("name" => "Belarus", "phone" => "375", "symbol" => "Br"),
    "BE" => array("name" => "Belgium", "phone" => "32", "symbol" => "€"),
    "BZ" => array("name" => "Belize", "phone" => "501", "symbol" => "$"),
    "BJ" => array("name" => "Benin", "phone" => "229", "symbol" => "CFA"),
    "BM" => array("name" => "Bermuda", "phone" => "1441", "symbol" => "$"),
    "BT" => array("name" => "Bhutan", "phone" => "975", "symbol" => "Nu."),
    "BO" => array("name" => "Bolivia", "phone" => "591", "symbol" => "Bs."),
    "BQ" => array("name" => "Bonaire, Sint Eustatius and Saba", "phone" => "599", "symbol" => "$"),
    "BA" => array("name" => "Bosnia and Herzegovina", "phone" => "387", "symbol" => "KM"),
    "BW" => array("name" => "Botswana", "phone" => "267", "symbol" => "P"),
    "BV" => array("name" => "Bouvet Island", "phone" => "55", "symbol" => "kr"),
    "BR" => array("name" => "Brazil", "phone" => "55", "symbol" => "R$"),
    "IO" => array("name" => "British Indian Ocean Territory", "phone" => "246", "symbol" => "$"),
    "BN" => array("name" => "Brunei Darussalam", "phone" => "673", "symbol" => "B$"),
    "BG" => array("name" => "Bulgaria", "phone" => "359", "symbol" => "Лв."),
    "BF" => array("name" => "Burkina Faso", "phone" => "226", "symbol" => "CFA"),
    "BI" => array("name" => "Burundi", "phone" => "257", "symbol" => "FBu"),
    "KH" => array("name" => "Cambodia", "phone" => "855", "symbol" => "KHR"),
    "CM" => array("name" => "Cameroon", "phone" => "237", "symbol" => "FCFA"),
    "CA" => array("name" => "Canada", "phone" => "1", "symbol" => "$"),
    "CV" => array("name" => "Cape Verde", "phone" => "238", "symbol" => "$"),
    "KY" => array("name" => "Cayman Islands", "phone" => "1345", "symbol" => "$"),
    "CF" => array("name" => "Central African Republic", "phone" => "236", "symbol" => "FCFA"),
    "TD" => array("name" => "Chad", "phone" => "235", "symbol" => "FCFA"),
    "CL" => array("name" => "Chile", "phone" => "56", "symbol" => "$"),
    "CN" => array("name" => "China", "phone" => "86", "symbol" => "¥"),
    "CX" => array("name" => "Christmas Island", "phone" => "61", "symbol" => "$"),
    "CC" => array("name" => "Cocos (Keeling) Islands", "phone" => "672", "symbol" => "$"),
    "CO" => array("name" => "Colombia", "phone" => "57", "symbol" => "$"),
    "KM" => array("name" => "Comoros", "phone" => "269", "symbol" => "CF"),
    "CG" => array("name" => "Congo", "phone" => "242", "symbol" => "FC"),
    "CD" => array("name" => "Congo, Democratic Republic of the Congo", "phone" => "242", "symbol" => "FC"),
    "CK" => array("name" => "Cook Islands", "phone" => "682", "symbol" => "$"),
    "CR" => array("name" => "Costa Rica", "phone" => "506", "symbol" => "₡"),
    "CI" => array("name" => "Cote D'Ivoire", "phone" => "225", "symbol" => "CFA"),
    "HR" => array("name" => "Croatia", "phone" => "385", "symbol" => "kn"),
    "CU" => array("name" => "Cuba", "phone" => "53", "symbol" => "$"),
    "CW" => array("name" => "Curacao", "phone" => "599", "symbol" => "ƒ"),
    "CY" => array("name" => "Cyprus", "phone" => "357", "symbol" => "€"),
    "CZ" => array("name" => "Czech Republic", "phone" => "420", "symbol" => "Kč"),
    "DK" => array("name" => "Denmark", "phone" => "45", "symbol" => "Kr."),
    "DJ" => array("name" => "Djibouti", "phone" => "253", "symbol" => "Fdj"),
    "DM" => array("name" => "Dominica", "phone" => "1767", "symbol" => "$"),
    "DO" => array("name" => "Dominican Republic", "phone" => "1809", "symbol" => "$"),
    "EC" => array("name" => "Ecuador", "phone" => "593", "symbol" => "$"),
    "EG" => array("name" => "Egypt", "phone" => "20", "symbol" => "ج.م"),
    "SV" => array("name" => "El Salvador", "phone" => "503", "symbol" => "$"),
    "GQ" => array("name" => "Equatorial Guinea", "phone" => "240", "symbol" => "FCFA"),
    "ER" => array("name" => "Eritrea", "phone" => "291", "symbol" => "Nfk"),
    "EE" => array("name" => "Estonia", "phone" => "372", "symbol" => "€"),
    "ET" => array("name" => "Ethiopia", "phone" => "251", "symbol" => "Nkf"),
    "FK" => array("name" => "Falkland Islands (Malvinas)", "phone" => "500", "symbol" => "£"),
    "FO" => array("name" => "Faroe Islands", "phone" => "298", "symbol" => "Kr."),
    "FJ" => array("name" => "Fiji", "phone" => "679", "symbol" => "FJ$"),
    "FI" => array("name" => "Finland", "phone" => "358", "symbol" => "€"),
    "FR" => array("name" => "France", "phone" => "33", "symbol" => "€"),
    "GF" => array("name" => "French Guiana", "phone" => "594", "symbol" => "€"),
    "PF" => array("name" => "French Polynesia", "phone" => "689", "symbol" => "₣"),
    "TF" => array("name" => "French Southern Territories", "phone" => "262", "symbol" => "€"),
    "GA" => array("name" => "Gabon", "phone" => "241", "symbol" => "FCFA"),
    "GM" => array("name" => "Gambia", "phone" => "220", "symbol" => "D"),
    "GE" => array("name" => "Georgia", "phone" => "995", "symbol" => "ლ"),
    "DE" => array("name" => "Germany", "phone" => "49", "symbol" => "€"),
    "GH" => array("name" => "Ghana", "phone" => "233", "symbol" => "GH₵"),
    "GI" => array("name" => "Gibraltar", "phone" => "350", "symbol" => "£"),
    "GR" => array("name" => "Greece", "phone" => "30", "symbol" => "€"),
    "GL" => array("name" => "Greenland", "phone" => "299", "symbol" => "Kr."),
    "GD" => array("name" => "Grenada", "phone" => "1473", "symbol" => "$"),
    "GP" => array("name" => "Guadeloupe", "phone" => "590", "symbol" => "€"),
    "GU" => array("name" => "Guam", "phone" => "1671", "symbol" => "$"),
    "GT" => array("name" => "Guatemala", "phone" => "502", "symbol" => "Q"),
    "GG" => array("name" => "Guernsey", "phone" => "44", "symbol" => "£"),
    "GN" => array("name" => "Guinea", "phone" => "224", "symbol" => "FG"),
    "GW" => array("name" => "Guinea-Bissau", "phone" => "245", "symbol" => "CFA"),
    "GY" => array("name" => "Guyana", "phone" => "592", "symbol" => "$"),
    "HT" => array("name" => "Haiti", "phone" => "509", "symbol" => "G"),
    "HM" => array("name" => "Heard Island and Mcdonald Islands", "phone" => "0", "symbol" => "$"),
    "VA" => array("name" => "Holy See (Vatican City State)", "phone" => "39", "symbol" => "€"),
    "HN" => array("name" => "Honduras", "phone" => "504", "symbol" => "L"),
    "HK" => array("name" => "Hong Kong", "phone" => "852", "symbol" => "$"),
    "HU" => array("name" => "Hungary", "phone" => "36", "symbol" => "Ft"),
    "IS" => array("name" => "Iceland", "phone" => "354", "symbol" => "kr"),
    "IN" => array("name" => "India", "phone" => "91", "symbol" => "₹"),
    "ID" => array("name" => "Indonesia", "phone" => "62", "symbol" => "Rp"),
    "IR" => array("name" => "Iran, Islamic Republic of", "phone" => "98", "symbol" => "﷼"),
    "IQ" => array("name" => "Iraq", "phone" => "964", "symbol" => "د.ع"),
    "IE" => array("name" => "Ireland", "phone" => "353", "symbol" => "€"),
    "IM" => array("name" => "Isle of Man", "phone" => "44", "symbol" => "£"),
    "IL" => array("name" => "Israel", "phone" => "972", "symbol" => "₪"),
    "IT" => array("name" => "Italy", "phone" => "39", "symbol" => "€"),
    "JM" => array("name" => "Jamaica", "phone" => "1876", "symbol" => "J$"),
    "JP" => array("name" => "Japan", "phone" => "81", "symbol" => "¥"),
    "JE" => array("name" => "Jersey", "phone" => "44", "symbol" => "£"),
    "JO" => array("name" => "Jordan", "phone" => "962", "symbol" => "ا.د"),
    "KZ" => array("name" => "Kazakhstan", "phone" => "7", "symbol" => "лв"),
    "KE" => array("name" => "Kenya", "phone" => "254", "symbol" => "KSh"),
    "KI" => array("name" => "Kiribati", "phone" => "686", "symbol" => "$"),
    "KP" => array("name" => "Korea, Democratic People's Republic of", "phone" => "850", "symbol" => "₩"),
    "KR" => array("name" => "Korea, Republic of", "phone" => "82", "symbol" => "₩"),
    "XK" => array("name" => "Kosovo", "phone" => "381", "symbol" => "€"),
    "KW" => array("name" => "Kuwait", "phone" => "965", "symbol" => "ك.د"),
    "KG" => array("name" => "Kyrgyzstan", "phone" => "996", "symbol" => "лв"),
    "LA" => array("name" => "Lao People's Democratic Republic", "phone" => "856", "symbol" => "₭"),
    "LV" => array("name" => "Latvia", "phone" => "371", "symbol" => "€"),
    "LB" => array("name" => "Lebanon", "phone" => "961", "symbol" => "£"),
    "LS" => array("name" => "Lesotho", "phone" => "266", "symbol" => "L"),
    "LR" => array("name" => "Liberia", "phone" => "231", "symbol" => "$"),
    "LY" => array("name" => "Libyan Arab Jamahiriya", "phone" => "218", "symbol" => "د.ل"),
    "LI" => array("name" => "Liechtenstein", "phone" => "423", "symbol" => "CHf"),
    "LT" => array("name" => "Lithuania", "phone" => "370", "symbol" => "€"),
    "LU" => array("name" => "Luxembourg", "phone" => "352", "symbol" => "€"),
    "MO" => array("name" => "Macao", "phone" => "853", "symbol" => "$"),
    "MK" => array("name" => "Macedonia, the Former Yugoslav Republic of", "phone" => "389", "symbol" => "ден"),
    "MG" => array("name" => "Madagascar", "phone" => "261", "symbol" => "Ar"),
    "MW" => array("name" => "Malawi", "phone" => "265", "symbol" => "MK"),
    "MY" => array("name" => "Malaysia", "phone" => "60", "symbol" => "RM"),
    "MV" => array("name" => "Maldives", "phone" => "960", "symbol" => "Rf"),
    "ML" => array("name" => "Mali", "phone" => "223", "symbol" => "CFA"),
    "MT" => array("name" => "Malta", "phone" => "356", "symbol" => "€"),
    "MH" => array("name" => "Marshall Islands", "phone" => "692", "symbol" => "$"),
    "MQ" => array("name" => "Martinique", "phone" => "596", "symbol" => "€"),
    "MR" => array("name" => "Mauritania", "phone" => "222", "symbol" => "MRU"),
    "MU" => array("name" => "Mauritius", "phone" => "230", "symbol" => "₨"),
    "YT" => array("name" => "Mayotte", "phone" => "269", "symbol" => "€"),
    "MX" => array("name" => "Mexico", "phone" => "52", "symbol" => "$"),
    "FM" => array("name" => "Micronesia, Federated States of", "phone" => "691", "symbol" => "$"),
    "MD" => array("name" => "Moldova, Republic of", "phone" => "373", "symbol" => "L"),
    "MC" => array("name" => "Monaco", "phone" => "377", "symbol" => "€"),
    "MN" => array("name" => "Mongolia", "phone" => "976", "symbol" => "₮"),
    "ME" => array("name" => "Montenegro", "phone" => "382", "symbol" => "€"),
    "MS" => array("name" => "Montserrat", "phone" => "1664", "symbol" => "$"),
    "MA" => array("name" => "Morocco", "phone" => "212", "symbol" => "DH"),
    "MZ" => array("name" => "Mozambique", "phone" => "258", "symbol" => "MT"),
    "MM" => array("name" => "Myanmar", "phone" => "95", "symbol" => "K"),
    "NA" => array("name" => "Namibia", "phone" => "264", "symbol" => "$"),
    "NR" => array("name" => "Nauru", "phone" => "674", "symbol" => "$"),
    "NP" => array("name" => "Nepal", "phone" => "977", "symbol" => "₨"),
    "NL" => array("name" => "Netherlands", "phone" => "31", "symbol" => "€"),
    "AN" => array("name" => "Netherlands Antilles", "phone" => "599", "symbol" => "NAf"),
    "NC" => array("name" => "New Caledonia", "phone" => "687", "symbol" => "₣"),
    "NZ" => array("name" => "New Zealand", "phone" => "64", "symbol" => "$"),
    "NI" => array("name" => "Nicaragua", "phone" => "505", "symbol" => "C$"),
    "NE" => array("name" => "Niger", "phone" => "227", "symbol" => "CFA"),
    "NG" => array("name" => "Nigeria", "phone" => "234", "symbol" => "₦"),
    "NU" => array("name" => "Niue", "phone" => "683", "symbol" => "$"),
    "NF" => array("name" => "Norfolk Island", "phone" => "672", "symbol" => "$"),
    "MP" => array("name" => "Northern Mariana Islands", "phone" => "1670", "symbol" => "$"),
    "NO" => array("name" => "Norway", "phone" => "47", "symbol" => "kr"),
    "OM" => array("name" => "Oman", "phone" => "968", "symbol" => ".ع.ر"),
    "PK" => array("name" => "Pakistan", "phone" => "92", "symbol" => "₨"),
    "PW" => array("name" => "Palau", "phone" => "680", "symbol" => "$"),
    "PS" => array("name" => "Palestinian Territory, Occupied", "phone" => "970", "symbol" => "₪"),
    "PA" => array("name" => "Panama", "phone" => "507", "symbol" => "B/."),
    "PG" => array("name" => "Papua New Guinea", "phone" => "675", "symbol" => "K"),
    "PY" => array("name" => "Paraguay", "phone" => "595", "symbol" => "₲"),
    "PE" => array("name" => "Peru", "phone" => "51", "symbol" => "S/."),
    "PH" => array("name" => "Philippines", "phone" => "63", "symbol" => "₱"),
    "PN" => array("name" => "Pitcairn", "phone" => "64", "symbol" => "$"),
    "PL" => array("name" => "Poland", "phone" => "48", "symbol" => "zł"),
    "PT" => array("name" => "Portugal", "phone" => "351", "symbol" => "€"),
    "PR" => array("name" => "Puerto Rico", "phone" => "1787", "symbol" => "$"),
    "QA" => array("name" => "Qatar", "phone" => "974", "symbol" => "ق.ر"),
    "RE" => array("name" => "Reunion", "phone" => "262", "symbol" => "€"),
    "RO" => array("name" => "Romania", "phone" => "40", "symbol" => "lei"),
    "RU" => array("name" => "Russian Federation", "phone" => "70", "symbol" => "₽"),
    "RW" => array("name" => "Rwanda", "phone" => "250", "symbol" => "FRw"),
    "BL" => array("name" => "Saint Barthelemy", "phone" => "590", "symbol" => "€"),
    "SH" => array("name" => "Saint Helena", "phone" => "290", "symbol" => "£"),
    "KN" => array("name" => "Saint Kitts and Nevis", "phone" => "1869", "symbol" => "$"),
    "LC" => array("name" => "Saint Lucia", "phone" => "1758", "symbol" => "$"),
    "MF" => array("name" => "Saint Martin", "phone" => "590", "symbol" => "€"),
    "PM" => array("name" => "Saint Pierre and Miquelon", "phone" => "508", "symbol" => "€"),
    "VC" => array("name" => "Saint Vincent and the Grenadines", "phone" => "1784", "symbol" => "$"),
    "WS" => array("name" => "Samoa", "phone" => "684", "symbol" => "SAT"),
    "SM" => array("name" => "San Marino", "phone" => "378", "symbol" => "€"),
    "ST" => array("name" => "Sao Tome and Principe", "phone" => "239", "symbol" => "Db"),
    "SA" => array("name" => "Saudi Arabia", "phone" => "966", "symbol" => "﷼"),
    "SN" => array("name" => "Senegal", "phone" => "221", "symbol" => "CFA"),
    "RS" => array("name" => "Serbia", "phone" => "381", "symbol" => "din"),
    "CS" => array("name" => "Serbia and Montenegro", "phone" => "381", "symbol" => "din"),
    "SC" => array("name" => "Seychelles", "phone" => "248", "symbol" => "SRe"),
    "SL" => array("name" => "Sierra Leone", "phone" => "232", "symbol" => "Le"),
    "SG" => array("name" => "Singapore", "phone" => "65", "symbol" => "$"),
    "SX" => array("name" => "Sint Maarten", "phone" => "1", "symbol" => "ƒ"),
    "SK" => array("name" => "Slovakia", "phone" => "421", "symbol" => "€"),
    "SI" => array("name" => "Slovenia", "phone" => "386", "symbol" => "€"),
    "SB" => array("name" => "Solomon Islands", "phone" => "677", "symbol" => "Si$"),
    "SO" => array("name" => "Somalia", "phone" => "252", "symbol" => "Sh.so."),
    "ZA" => array("name" => "South Africa", "phone" => "27", "symbol" => "R"),
    "GS" => array("name" => "South Georgia and the South Sandwich Islands", "phone" => "500", "symbol" => "£"),
    "SS" => array("name" => "South Sudan", "phone" => "211", "symbol" => "£"),
    "ES" => array("name" => "Spain", "phone" => "34", "symbol" => "€"),
    "LK" => array("name" => "Sri Lanka", "phone" => "94", "symbol" => "Rs"),
    "SD" => array("name" => "Sudan", "phone" => "249", "symbol" => ".س.ج"),
    "SR" => array("name" => "Suriname", "phone" => "597", "symbol" => "$"),
    "SJ" => array("name" => "Svalbard and Jan Mayen", "phone" => "47", "symbol" => "kr"),
    "SZ" => array("name" => "Swaziland", "phone" => "268", "symbol" => "E"),
    "SE" => array("name" => "Sweden", "phone" => "46", "symbol" => "kr"),
    "CH" => array("name" => "Switzerland", "phone" => "41", "symbol" => "CHf"),
    "SY" => array("name" => "Syrian Arab Republic", "phone" => "963", "symbol" => "LS"),
    "TW" => array("name" => "Taiwan, Province of China", "phone" => "886", "symbol" => "$"),
    "TJ" => array("name" => "Tajikistan", "phone" => "992", "symbol" => "SM"),
    "TZ" => array("name" => "Tanzania, United Republic of", "phone" => "255", "symbol" => "TSh"),
    "TH" => array("name" => "Thailand", "phone" => "66", "symbol" => "฿"),
    "TL" => array("name" => "Timor-Leste", "phone" => "670", "symbol" => "$"),
    "TG" => array("name" => "Togo", "phone" => "228", "symbol" => "CFA"),
    "TK" => array("name" => "Tokelau", "phone" => "690", "symbol" => "$"),
    "TO" => array("name" => "Tonga", "phone" => "676", "symbol" => "$"),
    "TT" => array("name" => "Trinidad and Tobago", "phone" => "1868", "symbol" => "$"),
    "TN" => array("name" => "Tunisia", "phone" => "216", "symbol" => "ت.د"),
    "TR" => array("name" => "Turkey", "phone" => "90", "symbol" => "₺"),
    "TM" => array("name" => "Turkmenistan", "phone" => "7370", "symbol" => "T"),
    "TC" => array("name" => "Turks and Caicos Islands", "phone" => "1649", "symbol" => "$"),
    "TV" => array("name" => "Tuvalu", "phone" => "688", "symbol" => "$"),
    "UG" => array("name" => "Uganda", "phone" => "256", "symbol" => "USh"),
    "UA" => array("name" => "Ukraine", "phone" => "380", "symbol" => "₴"),
    "AE" => array("name" => "United Arab Emirates", "phone" => "971", "symbol" => "إ.د"),
    "GB" => array("name" => "United Kingdom", "phone" => "44", "symbol" => "£"),
    "US" => array("name" => "United States", "phone" => "1", "symbol" => "$"),
    "UM" => array("name" => "United States Minor Outlying Islands", "phone" => "1", "symbol" => "$"),
    "UY" => array("name" => "Uruguay", "phone" => "598", "symbol" => "$"),
    "UZ" => array("name" => "Uzbekistan", "phone" => "998", "symbol" => "лв"),
    "VU" => array("name" => "Vanuatu", "phone" => "678", "symbol" => "VT"),
    "VE" => array("name" => "Venezuela", "phone" => "58", "symbol" => "Bs"),
    "VN" => array("name" => "Viet Nam", "phone" => "84", "symbol" => "₫"),
    "VG" => array("name" => "Virgin Islands, British", "phone" => "1284", "symbol" => "$"),
    "VI" => array("name" => "Virgin Islands, U.s.", "phone" => "1340", "symbol" => "$"),
    "WF" => array("name" => "Wallis and Futuna", "phone" => "681", "symbol" => "₣"),
    "EH" => array("name" => "Western Sahara", "phone" => "212", "symbol" => "MAD"),
    "YE" => array("name" => "Yemen", "phone" => "967", "symbol" => "﷼"),
    "ZM" => array("name" => "Zambia", "phone" => "260", "symbol" => "ZK"),
    "ZW" => array("name" => "Zimbabwe", "phone" => "263", "symbol" => "$")
);
?>